### ISSUE TITLE
Typos in code

### ISSUE THREAD

**Issue by TJHeuvel** [LotteMakesStuff/SimplePhysicsDemo#1]
https://github.com/LotteMakesStuff/SimplePhysicsDemo/blob/f65d020bfe988ec8cad15f3a593b3415db5f2988/Assets/SimpleJobifiedPhysics.cs#L15

https://en.wikipedia.org/wiki/Matrix_(mathematics)
`a matrix (plural: matrices)`

You're missing an r there! Super tiny, but its bugging me so much.

**Comment by TJHeuvel** [comment]
https://github.com/LotteMakesStuff/SimplePhysicsDemo/blob/f65d020bfe988ec8cad15f3a593b3415db5f2988/Assets/SimpleJobifiedPhysics.cs#L54

PrepairRaycastCommands  > PrepareRaycastCommands

**Comment by LotteMakesStuff** [comment]
Thanks for pointing this out - im dyslexic and spelling errors creep in easily! will get this fixed

**Comment by LotteMakesStuff** [comment]
these are now fixed in master branch
