### ISSUE TITLE
Exceptions thrown in current beta builds of Unity 2018.1

### ISSUE THREAD

**Issue by LotteMakesStuff** [LotteMakesStuff/SimplePhysicsDemo#2]
Unity throws thread safety exceptions disputed the fact the raycast jobs are scheduled with dependencies. This shouldn’t happen! Possible bug in Unity?

InvalidOperationException: The previously scheduled job SimpleJobifiedPhysics:PrepareRaycastCommands reads from the NativeArray PrepareRaycastCommands.Velocities. You are trying to schedule a new job SimpleJobifiedPhysics:GravityJob, which writes to the same NativeArray (via GravityJob.Velocities). To guarantee safety, you must include SimpleJobifiedPhysics:PrepareRaycastCommands as a dependency of the newly scheduled job.
http://Unity.Jobs.LowLevel.Unsafe.JobsUtility.ScheduleParallelFor (http://Unity.Jobs.LowLevel.Unsafe.JobScheduleParameters& parameters, Int32 arrayLength, Int32 innerloopBatchCount)
http://Unity.Jobs.IJobParallelForExtensions.Schedule[GravityJob] (GravityJob jobData, Int32 arrayLength, Int32 innerloopBatchCount, JobHandle dependsOn) (at C:/buildslave/unity/build/Runtime/Jobs/Managed/IJobParallelFor.cs:51)
SimpleJobifiedPhysics.Update () (at Assets/SimpleJobifiedPhysics.cs:212)

**Comment by olkeencole** [comment]
This is happening for me in 2018.1.0b8. :(

**Comment by LotteMakesStuff** [comment]
Bug in Unity - temporary workaround committed until Unitys fix lands in the beta. RaycastCommand ignores passed in dependencies. This was reported and fixed last month but didnt hit the public betas yet for some reason
